import os
import google.generativeai as genai

genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

MODEL_NAME = "models/gemini-flash-lite-latest"

def ask_gemini(system_prompt: str, user_prompt: str) -> str:
    """
    Gemini call for:
    - Plain language explanation
    - Risk reasoning
    - Renegotiation suggestions

    Uses FREE-TIER safe model.
    """

    model = genai.GenerativeModel(MODEL_NAME)

    prompt = f"""
You are a legal assistant for Indian small and medium business owners.
Explain clearly in simple business English.
Do NOT provide legal advice.

SYSTEM INSTRUCTIONS:
{system_prompt}

CONTENT:
{user_prompt}
"""

    try:
        response = model.generate_content(
            prompt,
            generation_config={
                "temperature": 0.2,
                "max_output_tokens": 600
            }
        )

        if not response or not response.text:
            return "⚠️ No response generated by Gemini."

        return response.text.strip()

    except Exception as e:
        return "⚠️ LLM unavailable. Falling back to rule-based analysis."
